# Generated by Django 3.2 on 2022-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20220608_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roplant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roplant',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
