# Generated by Django 3.2 on 2022-06-27 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20220620_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='userro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds', models.CharField(blank=True, max_length=100, null=True)),
                ('ph', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
