# Generated by Django 3.2 on 2022-06-27 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_userro_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userro',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
